### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by r0adax** [siketyan/freee-rs#16]
Hi, I'm sorry to bother you.
Can you help me contact Kento? He doesn't read the dm. 
Thank you.

**Comment by siketyan** [comment]
@r0adax
I have no relationship with him now cause I retired from Twitter, and can not help you with contacting him. Stop creating issues that is not related to the repository. Use Keybase (keybase.io/siketyan) or Discord (Siketyan#6289) if you want to contact me though.
